### ISSUE TITLE
IllegalArgumentException: Invalid step value 5 

### ISSUE THREAD

**Issue by leighayanid** [badoualy/stepper-indicator#2]
not working on api 15
# 

FATAL EXCEPTION: main
                                                                                    java.lang.IllegalArgumentException: Invalid step value 5
                                                                                        at com.badoualy.stepperindicator.StepperIndicator.setCurrentStep(StepperIndicator.java:272)
                                                                                        at com.badoualy.stepperindicator.StepperIndicator.onPageSelected(StepperIndicator.java:386)
                                                                                        at android.support.v4.view.ViewPager.dispatchOnPageSelected(ViewPager.java:1867)
                                                                                        at android.support.v4.view.ViewPager.scrollToItem(ViewPager.java:625)
                                                                                        at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:609)
                                                                                        at android.support.v4.view.ViewPager.onTouchEvent(ViewPager.java:2181)
                                                                                        at android.view.View.dispatchTouchEvent(View.java:5629)
                                                                                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:1964)
                                                                                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1725)
                                                                                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:1970)
                                                                                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1739)
                                                                                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:1970)
                                                                                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1739)
                                                                                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:1970)
                                                                                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1739)
                                                                                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:1970)
                                                                                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1739)
                                                                                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:1970)
                                                                                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1739)
                                                                                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:1970)
                                                                                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1739)
                                                                                        at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2062)
                                                                                        at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1400)
                                                                                        at android.app.Activity.dispatchTouchEvent(Activity.java:2369)
                                                                                        at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:60)
                                                                                        at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2010)
                                                                                        at android.view.View.dispatchPointerEvent(View.java:5809)
                                                                                        at android.view.ViewRootImpl.deliverPointerEvent(ViewRootImpl.java:3126)
                                                                                        at android.view.ViewRootImpl.handleMessage(ViewRootImpl.java:2654)
                                                                                        at android.view.ViewRootImpl.processInputEvents(ViewRootImpl.java:1015)
                                                                                        at android.view.ViewRootImpl.handleMessage(ViewRootImpl.java:2663)
                                                                                        at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                        at android.os.Looper.loop(Looper.java:137)
                                                                                        at android.app.ActivityThread.main(ActivityThread.java:4517)
                                                                                        at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                        at java.lang.reflect.Method.invoke(Method.java:511)
                                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:993)
                                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:760)
                                                                                        at dalvik.system.NativeStart.main(Native Method)

**Comment by badoualy** [comment]
Indeed, bugged when keeping last page as a "finishing page" :smile: 

See v1.0.1
