### ISSUE TITLE
Crashes while setting  indicator.showLabels(true);

### ISSUE THREAD

**Issue by cidaas** [badoualy/stepper-indicator#45]
09-06 12:51:32.797 28993-28993/company.voicedemoapp E/AndroidRuntime: FATAL EXCEPTION: main
                                                                  
                                                                      java.lang.NullPointerException
                                                                          at com.badoualy.stepperindicator.StepperIndicator.calculateMaxLabelHeight(StepperIndicator.java:823)
                                                                          at com.badoualy.stepperindicator.StepperIndicator.onMeasure(StepperIndicator.java:1056)
                                                                          at android.view.View.measure(View.java:16749)
                                                                          at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:719)
                                                                          at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:455)
                                                                          at android.view.View.measure(View.java:16749)
                                                                          at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5295)
                                                                          at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
                                                                          at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:139)
                                                                          at android.view.View.measure(View.java:16749)
                                                                          at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5295)
                                                                          at android.support.v7.widget.ActionBarOverlayLayout.onMeasure(ActionBarOverlayLayout.java:391)
                                                                          at android.view.View.measure(View.java:16749)
                                                                          at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5295)
                                                                          at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
                                                                          at android.view.View.measure(View.java:16749)
                                                                          at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5295)
                                                                          at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
                                                                          at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
                                                                          at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
                                                                          at android.view.View.measure(View.java:16749)
                                                                          at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5295)
                                                                          at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
                                                                          at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2439)
                                                                          at android.view.View.measure(View.java:16749)
                                                                          at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2080)
                                                                          at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1176)
                                                                          at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1380)
                                                                          at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1063)
                                                                          at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5993)
                                                                          at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
                                                                          at android.view.Choreographer.doCallbacks(Choreographer.java:574)
                                                                          at android.view.Choreographer.doFrame(Choreographer.java:544)
                                                                          at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
                                                                          at android.os.Handler.handleCallback(Handler.java:733)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                          at android.os.Looper.loop(Looper.java:136)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5584)
                                                                          at java.lang.reflect.Method.invokeNative(Native Method)
                                                                          at java.lang.reflect.Method.invoke(Method.java:515)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
                                                                          at dalvik.system.NativeStart.main(Native Method)

**Comment by badoualy** [comment]
Why did you close it?
